name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '2.2.1'

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-py3.14-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-py3.14-poetry-

      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-ansi

      - name: Run full test suite
        run: |
          poetry run make run-ci-pipeline



